### ISSUE TITLE
请问能获取设备自身的mac地址么

### ISSUE THREAD

**Issue by harryzhao2015** [MacPu/BluetoothMacAddressDemo#4]
能获取到iPhone自身的mac地址么

**Comment by MacPu** [comment]
iOS7.0之后无法获取自身的Mac地址了，获取到的地址都是20:00:00:00:00

**Comment by harryzhao2015** [comment]
我没说明白，设备自身蓝牙的mac地址？

**Comment by MacPu** [comment]
也是iOS7.0之后禁掉了，你可以搜索如何获取Linux蓝牙地址，最后获得的地址也是20:00:00:00:00。如果你是想通过mac地址去连接iPhone，这个目前行不通，但是你可以根据蓝牙名去连接iPhone，iPhone的蓝牙名是设备名
